// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    
		int num = Integer.parseInt(args[0]);
		int i = 0;
		int count_min = 0;
		int count_max = 0;
		Double random_num;
		while(i != num){
			random_num = Math.random();
			if(random_num <= 0.5){
				count_min = count_min + 1;
			}
			else{
				count_max = count_max + 1;
			}
			i = i + 1;
		}
		System.out.println("> 0.5: " + count_max + " times");
		System.out.println("<= 0.5: " + count_min + " times");
		if(count_max == 0 || count_min == 0){
			
		}
		else{
			double ratio = (double)count_max/count_min;
			System.out.println(ratio);
		}
		
		
	}
}
